# https://github.com/golangci/golangci-lint
name: golang_lint_and_test
on: [push, pull_request]
jobs:
  golang_lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "actualy,nwe"
          skip: "go.mod,go.sum"
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E gofmt
      - name: Run tests
        run: go test ./...
